# Laboratory work 3.3

### Flat diffraction grating.

Objectives:
1. Calculate 12 values of d.
2. Calculate the average d.
3. Calculate the random error of d.
4. Compare your obtained d value to the given value. Does the given value fall in the range
of your random error of d?
5. What are the main sources of errors? What are your suggestions for improvements?

### Summary

* **This laboratory work studied the properties of a diffraction grating.** The grating constant depends on the wavelength and the angle.

* **The constant of the grating d = 8.96 Â± 0.19 micro meters.** To improve the accuracy, consider making more observations per order of spectrum to capture the random error at each angle measurement step to filter out mismeasured observations and get better statistical power for the average.

In [1]:
import pandas as pd
import numpy as np

### Experiment setting

* Element: mercury $ \rightarrow \lambda = 4.35 \cdot 10^{-7} m $

In [2]:
spectrometer_angle_error_deg = 0.01
spectrometer_angle_error_rad = np.deg2rad(spectrometer_angle_error_deg)
lambda_m = 4.35e-7

### Read observations
* Convert angle $ \phi $ to radians

In [3]:
df = pd.read_csv("lab_3_3_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   order_of_spectrum_k           12 non-null     int64
 1   wavelength_m                  12 non-null     float64
 2   angle_of_observation_degrees  12 non-null     int64
 3   angle_of_observation_minutes  12 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 516.0 bytes

In [4]:
def deg_to_rad(row: pd.Series) -> float:
    """Convert deg with minutes to rad."""
    angle_deg = row["angle_of_observation_degrees"] + row["angle_of_observation_minutes"] / 60
    return np.deg2rad(angle_deg)

df["angle_of_observation_rad"] = df.apply(deg_to_rad, axis=1)

### Find distance $ d $ between equal points in the adjacent slits

* $ d sin(\phi)=k \lambda \rightarrow d = \frac{k \lambda}{sin(\phi)} $

In [5]:
def calculate_d(row: pd.Series) -> float:
    """Convert deg with minutes to rad."""
    k = row["order_of_spectrum_k"]
    wavelength = row["wavelength_m"]
    angle_rad = row["angle_of_observation_rad"]
    return (k * wavelength) / np.sin(angle_rad)

df["d_m"] = df.apply(calculate_d, axis=1)
df

,order_of_spectrum_k,wavelength_m,angle_of_observation_degrees,angle_of_observation_minutes,angle_of_observation_rad,d_m
0,1,4.350000e-07,2,30,0.043633,0.000010
1,2,4.350000e-07,5,5,0.088721,0.000010
2,3,4.350000e-07,6,36,0.115192,0.000011
3,4,4.350000e-07,10,10,0.177442,0.000010
4,5,4.350000e-07,15,30,0.270526,0.000008
5,6,4.350000e-07,18,10,0.317068,0.000008
6,7,4.350000e-07,21,55,0.382518,0.000008
7,8,4.350000e-07,23,30,0.410152,0.000009
8,9,4.350000e-07,26,20,0.459603,0.000009
9,10,4.350000e-07,29,25,0.513418,0.000009
10,11,4.350000e-07,32,30,0.567232,0.000009
11,12,4.350000e-07,35,40,0.622501,0.000009

### Calculate random error of $ d $

In [6]:
num_observations = len(df["d_m"])
mean_d = np.mean(df["d_m"])
std_d = np.std(df["d_m"])
random_error = std_d / np.sqrt(num_observations)

In [7]:
def is_trustworthy(d):
    """Check gross error."""
    return abs(d - mean_d) < 6 * random_error

df["is_trustworthy"] = df["d_m"].apply(is_trustworthy)
df

,order_of_spectrum_k,wavelength_m,angle_of_observation_degrees,angle_of_observation_minutes,angle_of_observation_rad,d_m,is_trustworthy
0,1,4.350000e-07,2,30,0.043633,0.000010,True
1,2,4.350000e-07,5,5,0.088721,0.000010,True
2,3,4.350000e-07,6,36,0.115192,0.000011,False
3,4,4.350000e-07,10,10,0.177442,0.000010,True
4,5,4.350000e-07,15,30,0.270526,0.000008,True
5,6,4.350000e-07,18,10,0.317068,0.000008,True
6,7,4.350000e-07,21,55,0.382518,0.000008,True
7,8,4.350000e-07,23,30,0.410152,0.000009,True
8,9,4.350000e-07,26,20,0.459603,0.000009,True
9,10,4.350000e-07,29,25,0.513418,0.000009,True
10,11,4.350000e-07,32,30,0.567232,0.000009,True
11,12,4.350000e-07,35,40,0.622501,0.000009,True

Filter out third observation.

In [8]:
df = df.drop(2)
df.reset_index(inplace=True)
num_observations = len(df["d_m"])
mean_d = np.mean(df["d_m"])
std_d = np.std(df["d_m"])
random_error = std_d / np.sqrt(num_observations)
df["is_trustworthy"] = df["d_m"].apply(is_trustworthy)
df

,index,order_of_spectrum_k,wavelength_m,angle_of_observation_degrees,angle_of_observation_minutes,angle_of_observation_rad,d_m,is_trustworthy
0,0,1,4.350000e-07,2,30,0.043633,0.000010,True
1,1,2,4.350000e-07,5,5,0.088721,0.000010,True
2,3,4,4.350000e-07,10,10,0.177442,0.000010,True
3,4,5,4.350000e-07,15,30,0.270526,0.000008,True
4,5,6,4.350000e-07,18,10,0.317068,0.000008,True
5,6,7,4.350000e-07,21,55,0.382518,0.000008,True
6,7,8,4.350000e-07,23,30,0.410152,0.000009,True
7,8,9,4.350000e-07,26,20,0.459603,0.000009,True
8,9,10,4.350000e-07,29,25,0.513418,0.000009,True
9,10,11,4.350000e-07,32,30,0.567232,0.000009,True
10,11,12,4.350000e-07,35,40,0.622501,0.000009,True

In [9]:
print(f"The constant of the grating d = {mean_d*1e6:.2f} Â± {random_error*1e6:.2f} [micro m]")

The constant of the grating d = 8.96 Â± 0.19 [micro m]

---

&nbsp;

# Conclusions

* **This laboratory work studied the properties of a diffraction grating.** The grating constant depends on the wavelength and the angle.

* **The constant of the grating d = 8.96 Â± 0.19 micro meters.** To improve the accuracy, consider making more observations per order of spectrum to capture the random error at each angle measurement step to filter out mismeasured observations and get better statistical power for the average.